name: Deploy to PyPI

on:
  push:
    tags: ["v*"]

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pdflex
    permissions:
      id-token: write

    steps:
      - uses: ./.github/workflows/checkout

      - name: Set up Python
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish to PyPI
        uses: ./.github/workflows/pypi-publish
        with:
          packages-dir: dist/