name: Version Bump
on:
  release:
    types: [created]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version
        run: |
          # Extract version from release tag
          VERSION=${GITHUB_REF#refs/tags/v}
          # Update version in __init__.py
          sed -i "s/__version__ = .*/__version__ = \"$VERSION\"/" src/pdflex/__init__.py
